### ISSUE TITLE
v3.0.13 not published

### ISSUE THREAD

**Issue by acreighton** [loktar00/react-lazy-load#113]
The fix for #110 has not been published yet.

![npm](https://user-images.githubusercontent.com/1289730/31791373-5e47d9c4-b4e6-11e7-84cc-a610d4af6eef.png)

**Comment by michaelchance** [comment]
+1, It would be really great to get React 16 support into the peerDependencies so I can shrinkwrap my app.

**Comment by sergeylaptev** [comment]
Fixed:)

**Comment by dschinkel** [comment]
still does not work for React 16. [116](https://github.com/loktar00/react-lazy-load/issues/116)
