### ISSUE TITLE
Issue with updating the React to 15.0.1

### ISSUE THREAD

**Issue by ateev** [loktar00/react-lazy-load#53]
NPM fails when trying to update the React. Is this because of `react-lazy-load` ?

```
npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-lazy-load@3.0.7 wants react@^0.14.0
npm ERR! peerinvalid Peer react-redux@4.0.1 wants react@^0.14.0
```

**Comment by sergeylaptev** [comment]
Was fixed in #e4f82862cd6a5385dd5548af5b62175561dc01c0.
3.0.8 is already in npm

**Comment by ateev** [comment]
@sergeylaptev Thanks for the help. But I'm still getting the same error.

```
npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-lazy-load@3.0.8 wants react@^0.14.0
npm ERR! peerinvalid Peer react-redux@4.4.2 wants react@^0.14.0 || ^15.0.0-0
```

**Comment by sergeylaptev** [comment]
Try this:
```
rm -rf node_modules
npm install
```

**Comment by ateev** [comment]
Tried. Didn't help :disappointed:

**Comment by sergeylaptev** [comment]
Ok, my bad. I've changed package.json too fast and didn't catch typo:) I'll publish 3.0.8 as soon as possible, and open this issue until it will be fixed.

**Comment by ateev** [comment]
Also, do we need to update `react-dom` too ? https://github.com/loktar00/react-lazy-load/blob/master/package.json#L59

**Comment by sergeylaptev** [comment]
yep, already updated this.

**Comment by sergeylaptev** [comment]
I've published 3.0.9, just checked and everything works fine with 15.0.1

**Comment by ateev** [comment]
That fixed the issue. Thanks !
